services:
  web-service:
    container_name: web-service
    build:
      context: .
      dockerfile: Dockerfile
    image: node_web
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./html/:/web_service/frontEnd/dist/
    command: sh -c "npm run start:prod --workspaces"

  nginx:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - 3001:80
    links:
      - web-service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
